[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.13",
    "asyncio-mqtt>=0.16.2",
    "cryptography>=45.0.5",
    "flask>=3.1.1",
    "jinja2>=3.1.6",
    "pillow>=11.3.0",
    "python-dateutil>=2.9.0.post0",
    "python-telegram-bot>=22.2",
    "qrcode[pil]>=8.2",
    "requests>=2.32.4",
    "telegram>=0.0.1",
    "wtforms>=3.2.1",
]
